spring:
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/