spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/students/**
        - id: products
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**

eureka:
  client:
    register-with-eureka: false

server:
  port: 8202