spring:
  data:
    redis:
      host: ${LHOST}
      port: ${REDIS_PORT}
      timeout: 2000ms

jwt:
  accessToken:
    secret: ${ACCESS_TOKEN_SECRET}
    cookieName: access_token
    maxAge: 900000 # 15 minutes
    secured: false
  refreshToken:
    secret: ${REFRESH_TOKEN_SECRET}
    cookieName: refresh_token
    maxAge: 1209600000 # 15 days
    secured: false