x-common-service: &common-service
  networks:
    ecommerce-net:
  restart: unless-stopped
  stdin_open: true
  tty: true

x-database-healthcheck: &database-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 60s

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      <<: *database-healthcheck

  redis:
    image: redis:8.6.2-alpine
    environment:
      REDISCLI_USER: ${REDIS_USER}
      REDISCLI_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    <<: *common-service
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      <<: *database-healthcheck


volumes:
  postgres_data:
  redis_data:

networks:
  ecommerce-net:
    external: true