x-common-env: &common-env
  DISCOVERY_SERVER: discovery-server
  DISCOVERY_SERVER_PORT: 8080

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 90s

x-common-service: &common-service
  networks:
    ecommerce-net:
  restart: unless-stopped
  stdin_open: true
  tty: true

services:
  discovery-server:
    image: abdelaziz333/discovery-server:0.1
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    ports:
      - "${DISCOVERY_SERVER_PORT}:${DISCOVERY_SERVER_PORT}"
    environment:
      <<: *common-env
      PORT: ${DISCOVERY_SERVER_PORT}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${DISCOVERY_SERVER_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  api-gateway:
    image: abdelaziz333/api-gateway:0.1
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      <<: *common-env
      PORT: ${API_GATEWAY_PORT}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${API_GATEWAY_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  auth-service:
    image: abdelaziz333/auth-service:0.1
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "${AUTH_SVC_PORT}:${AUTH_SVC_PORT}"
    environment:
      <<: *common-env
      PORT: ${AUTH_SVC_PORT}
      POSTGRES_DB: auth
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${AUTH_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  product-service:
    image: abdelaziz333/product-service:0.1
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "${PRODUCT_SVC_PORT}:${PRODUCT_SVC_PORT}"
    environment:
      <<: *common-env
      PORT: ${PRODUCT_SVC_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${PRODUCT_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  cart-service:
    image: abdelaziz333/cart-service:0.1
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    ports:
      - "${CART_SVC_PORT}:${CART_SVC_PORT}"
    environment:
      <<: *common-env
      PORT: ${CART_SVC_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_DB: cart
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${CART_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  order-service:
    image: abdelaziz333/order-service:0.1
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "${ORDER_SVC_PORT}:${ORDER_SVC_PORT}"
    environment:
      <<: *common-env
      PORT: ${ORDER_SVC_PORT}
      POSTGRES_DB: order
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${ORDER_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  payment-service:
    image: abdelaziz333/payment-service:0.1
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "${PAYMENT_SVC_PORT}:${PAYMENT_SVC_PORT}"
    environment:
      <<: *common-env
      PORT: ${PAYMENT_SVC_PORT}
      POSTGRES_DB: payment
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${PAYMENT_POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${PAYMENT_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  notification-service:
    image: abdelaziz333/notification-service:0.1
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "${NOTIFICATION_SVC_PORT}:${NOTIFICATION_SVC_PORT}"
    environment:
      <<: *common-env
      PORT: ${NOTIFICATION_SVC_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${NOTIFICATION_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

networks:
  ecommerce-net:
    external: true