x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 90s

x-common-service: &common-service
  networks:
    ecommerce-net:
  restart: unless-stopped

services:
  api-gateway:
    image: abdelaziz333/api-gateway:0.0.1
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      PORT: ${API_GATEWAY_PORT}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${API_GATEWAY_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - all
      - app

  product-service:
    image: abdelaziz333/product-service:0.0.1
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "${PRODUCT_SVC_PORT}:${PRODUCT_SVC_PORT}"
    environment:
      PORT: ${PRODUCT_SVC_PORT}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${PRODUCT_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - all
      - app

  order-service:
    image: abdelaziz333/order-service:0.0.1
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "${ORDER_SVC_PORT}:${ORDER_SVC_PORT}"
    environment:
      PORT: ${ORDER_SVC_PORT}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${ORDER_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - all
      - app

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: aziz333
    <<: *common-service
    profiles:
      - all
      - database

  redis:
    image: redis:8.6.2-alpine
    ports:
      - "6379:6379"
    <<:  *common-service
    profiles:
      - all
      - database

volumes:
  postgres_data:

networks:
  ecommerce-net:
    external: true