x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 90s

x-common-service: &common-service
  networks:
    ecommerce-net:
  restart: unless-stopped
  stdin_open: true
  tty: true

x-database-healthcheck: &database-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 60s

services:
  api-gateway:
    image: abdelaziz333/api-gateway:0.1
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      PORT: ${API_GATEWAY_PORT}
      POSTGRES_DB: auth
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_USER: ${REDIS_APP_USER}
      REDIS_PASSWORD: ${REDIS_APP_PASSWORD}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${API_GATEWAY_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  product-service:
    image: abdelaziz333/product-service:0.1
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "${PRODUCT_SVC_PORT}:${PRODUCT_SVC_PORT}"
    environment:
      PORT: ${PRODUCT_SVC_PORT}
      POSTGRES_DB: product
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${PRODUCT_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  order-service:
    image: abdelaziz333/order-service:0.1
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "${ORDER_SVC_PORT}:${ORDER_SVC_PORT}"
    environment:
      PORT: ${ORDER_SVC_PORT}
      POSTGRES_DB: order
      POSTGRES_USER: aziz
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_USER: ${REDIS_APP_USER}
      REDIS_PASSWORD: ${REDIS_APP_PASSWORD}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${ORDER_SVC_PORT}/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      <<: *database-healthcheck
    profiles:
      - database
      - all

  redis:
    image: redis:8.6.2-alpine
    environment:
      REDISCLI_USER: ${REDIS_USER}
      REDISCLI_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    <<: *common-service
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      <<: *database-healthcheck
    profiles:
      - database
      - all

volumes:
  postgres_data:
  redis_data:

networks:
  ecommerce-net:
    external: true