x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 90s

x-common-service: &common-service
  networks:
    ecommerce-net:
  restart: unless-stopped

services:
  discovery-server:
    image: abdelaziz333/discovery-server:0.0.1
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  api-gateway:
    image: abdelaziz333/api-gateway:0.0.1
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8081:8081"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  auth-service:
    image: abdelaziz333/auth-service:0.0.1
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    ports:
      - "8082:8082"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8082/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  product-service:
    image: abdelaziz333/product-service:0.0.1
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "8083:8083"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8083/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  cart-service:
    image: abdelaziz333/cart-service:0.0.1
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
    ports:
      - "8084:8084"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8084/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  order-service:
    image: abdelaziz333/order-service:0.0.1
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "8085:8085"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8085/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  payment-service:
    image: abdelaziz333/payment-service:0.0.1
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    ports:
      - "8086:8086"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8086/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

  notification-service:
    image: abdelaziz333/notification-service:0.0.1
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "8087:8087"
    <<: *common-service
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8087/actuator/health" ]
      <<: *common-healthcheck
    profiles:
      - app
      - all

networks:
  ecommerce-net:
    external: true