x-common-service: &common-service
  networks:
    ecommerce-net:
  restart: unless-stopped
  stdin_open: true
  tty: true

x-database-healthcheck: &database-healthcheck
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 60s

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    <<: *common-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      <<: *database-healthcheck

  redis:
    image: redis:8.6.2-alpine
    environment:
      REDISCLI_USER: ${REDIS_USER}
      REDISCLI_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    <<: *common-service
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      <<: *database-healthcheck

  mongo:
    image: mongo:8.3
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    <<: *common-service
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      <<: *database-healthcheck

  kafka:
    image: apache/kafka:4.3.1
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    <<: *common-service
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  prometheus:
    image: prom/prometheus:v3
    ports:
      - "9090:9090"
    volumes:
      - ./infra/observability/prometheus/prometheus-prod.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    <<: *common-service
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  grafana:
    image: grafana/grafana:13.1-slim
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: aziz
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/observability/grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./infra/observability/grafana/provisioning/dashboards/json:/var/lib/grafana/dashboards
      - ./infra/observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    <<: *common-service
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Exporters

  node-exporter:
    image: prom/node-exporter:v1.10.2
    <<: *common-service

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"
    <<: *common-service
    depends_on:
      postgres:
        condition: service_healthy

  redis-exporter:
    image: oliver006/redis_exporter:v1.80.1-alpine
    environment:
      REDIS_ADDR: "redis://${REDIS_USER}:${REDIS_PASSWORD}@redis:6379"
    <<: *common-service
    depends_on:
      redis:
        condition: service_healthy

  mongo-exporter:
    image: percona/mongodb_exporter:0.47.2
    command:
      - "--mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/admin?authSource=admin"
    <<: *common-service
    depends_on:
      product-mongo:
        condition: service_healthy

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    command:
      - "--kafka.server=kafka:9092"
    <<: *common-service
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  kafka_data:
  grafana_data:

networks:
  ecommerce-net:
    external: true