spring:
  data:
    mongodb:
      host: ${LHOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DB}
      authentication-database: admin
    elasticsearch:
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      uris:
        - http://${LHOST}:${ELASTIC_HTTP_PORT}

server:
  port: 8081