global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8080']
        labels:
          service: 'discovery-server'

      - targets: ['auth-service:8081']
        labels:
          service: 'auth-service'

      - targets: ['product-service:8082']
        labels:
          service: 'product-service'

      - targets: ['cart-service:8083']
        labels:
          service: 'cart-service'

      - targets: ['order-service:8084']
        labels:
          service: 'order-service'

      - targets: ['payment-service:8085']
        labels:
          service: 'payment-service'

      - targets: ['notification-service:8086']
        labels:
          service: 'notification-service'

      - targets: ['api-gateway:8087']
        labels:
          service: 'api-gateway'

  - job_name: 'exporters'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres-exporter'

      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis-exporter'

      - targets: ['mongo-exporter:9216']
        labels:
          service: 'mongo-exporter'

      - targets: ['kafka-exporter:9308']
        labels:
          service: 'kafka-exporter'