spring:
  mongodb:
    host: mongo
    database: ${MONGO_DB}
    username: aziz
    password: ${MONGO_PASSWORD}
    authentication-database: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8080/eureka/