CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    short_description VARCHAR(255),
    sku VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) UNIQUE,
    price DOUBLE PRECISION NOT NULL,
    stock_quantity INT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE product_variant_attributes (
    product_id BIGINT NOT NULL,
    attribute VARCHAR(255),
    CONSTRAINT fk_product_variant_attributes_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);